# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nate S. Holland
email: natesholland@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I write things for humans and computers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://natesholland.github.io/" # the base hostname & protocol for your site
twitter_username: natesholland
github_username: natesholland
include: ["_pages"]
permalink: /:title/

# Build settings
markdown: kramdown
